manual: Beamer_presentation_template.tex 
	pdflatex Beamer_presentation_template.tex
	pdflatex Beamer_presentation_template.tex
	cp Beamer_presentation_template.pdf Beamer_presentation_template_1.pdf
	evince Beamer_presentation_template_1.pdf&

clean:
	rm -f *.aux
	rm -f *.log
	rm -f *.ps
	rm -f *.dvi
	rm -f *.toc
	rm -f *.lof
	rm -f *.nav
	rm -f *.out
	rm -f *.snm
	rm -f *.blg
	rm -f *.acn
	rm -f *.ist
	rm -f *.lot
	rm -f *.glo
	rm -f *.gls
	rm -f *.glg
	rm -f *.alg
	rm -f *.idx
	rm -f *.bbl
	rm -f *.acr
	rm -f *.pdf
